export const products = [
  {
    id: 1,
    name: "Samsung Galaxy Watch 6",
    category: "Tecnologia",
    desc: "Smartwatch Samsung para saúde, notificações e exercícios.",
    price: "R$ 1.500+",
    color: "bg-blue-500/20 text-blue-400",
    image: "/relogio.jfif",
    link: "https://www.mercadolivre.com.br/smartwatch-samsung-galaxy-watch6-bt-40mm-tela-super-amoled-de-131-grafite/p/MLB25397313",
  },
  {
    id: 2,
    name: "SSD 256 GB",
    category: "Tecnologia",
    desc: "SSD SATA ou NVMe de 256 GB para melhorar o desempenho do computador.",
    price: "R$ 150+",
    color: "bg-blue-500/20 text-blue-400",
    image: "/ssd.jpg",
    link: "https://www.kabum.com.br/hardware/ssd-2-5/ssd-sata",
  },
  {
    id: 3,
    name: "Roupa de Academia",
    category: "Vestuário",
    desc: "Conjunto confortável para treinos.",
    price: "R$ 200+",
    color: "bg-orange-500/20 text-orange-400",
    image: "/gym.jpg",
    link: "https://www.centauro.com.br/",
  },
  {
    id: 4,
    name: "Perfume Kaiak Oceano",
    category: "Perfume",
    desc: "Fragrância masculina refrescante da Natura.",
    price: "R$ 150+",
    color: "bg-purple-500/20 text-purple-400",
    image: "/oceano.jpg",
    link: "https://www.natura.com.br/p/desodorante-colonia-kaiak-oceano-masculino-promocao-vai-dar-onda-100-ml/NATBRA-246412",
  },
  {
    id: 5,
    name: "Malbec Black Bleu",
    category: "Perfume",
    desc: "Perfume masculino sofisticado do Boticário.",
    price: "R$ 250+",
    color: "bg-purple-500/20 text-purple-400",
    image: "/bleu.webp",
    link: "https://www.boticario.com.br/malbec-bleu-desodorante-colonia-100ml/",
  },
  {
    id: 7,
    name: "Jaqueta Bobojaco Masculina",
    category: "Vestuário",
    desc: "Jaqueta de inverno masculina forrada.",
    price: "R$ 300+",
    color: "bg-orange-500/20 text-orange-400",
    image: "/bobojaco.jfif",
    link: "https://produto.mercadolivre.com.br/MLB-5338159472-jaqueta-bobojaco-casaco-forrada-inverno-intenso-neve-frio-_JM",
  },
  {
    id: 8,
    name: "Nike Dunk Low",
    category: "Calçados",
    desc: "Tênis casual Nike Dunk Low.",
    price: "R$ 900+",
    color: "bg-emerald-500/20 text-emerald-400",
    image: "/nike.webp",
    link: "https://www.nike.com.br/dunk-low-097554.html",
  },
  {
    id: 9,
    name: "Blusa do Brasil",
    category: "Vestuário",
    desc: "Camisa oficial da Seleção Brasileira preta e azul.",
    price: "R$ 300+",
    color: "bg-yellow-500/20 text-yellow-400",
    image: "/brasil.webp",
    link: "https://www.nike.com.br/camisa-brasil-jordan-ii-2026-27-torcedor-pro-masculina-097617.html?cor=15",
  },
];

export const receivedCount = 0;

export const categories = [...new Set(products.map((p) => p.category))];
